services:
  backend:
    build:
      context: ./Backend/EMSTUDY
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    build:
      context: .
      dockerfile: frontend/Emstudy/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"