name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:
    name: Build & Test Backend
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: appdb
          MYSQL_USER: user
          MYSQL_PASSWORD: pass
          MYSQL_ROOT_PASSWORD: rootpass
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping -h localhost -u root -prootpass" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Maven clean & verify
        env:
          DB_HOST: localhost
          DB_PORT: 3307
          DB_NAME: appdb
          DB_USERNAME: user
          DB_PASSWORD: pass
        run: |
          cd Backend/EMSTUDY
          mvn -B clean verify

  build-frontend:
    name: Build & Test Frontend
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List directory contents
        run: |
          pwd
          ls -la
          ls -la Frontend/Emstudy

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: Frontend/Emstudy/package-lock.json

      - name: Install dependencies
        working-directory: Frontend/Emstudy
        run: npm install

      - name: Build React app
        working-directory: Frontend/Emstudy
        run: npm run build
